# Generated by Django 3.2.3 on 2021-05-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_app', '0002_first_app_is_helpless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_app',
            name='is_helpless',
            field=models.BooleanField(default=True),
        ),
    ]
